-- Hub Seja Meu Sócio — Supabase PostgreSQL
-- Execute no SQL Editor do projeto Supabase correto.

create table if not exists public.hub_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hub_projects (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 140),
  description text not null check (char_length(description) between 8 and 2500),
  price numeric(12,2) not null default 0 check (price >= 0),
  kind text not null check (kind in ('free', 'paid')),
  project_url text not null,
  cover_url text,
  cover_key text,
  media_kind text not null default 'image' check (media_kind in ('image', 'video', 'iframe')),
  video_url text,
  video_key text,
  iframe_url text,
  created_by uuid references public.hub_profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint paid_projects_need_price check (kind = 'free' or price > 0),
  constraint projects_need_cover check (cover_url is not null and char_length(cover_url) > 0),
  constraint video_projects_need_video check (media_kind <> 'video' or video_url is not null),
  constraint iframe_projects_need_url check (media_kind <> 'iframe' or iframe_url is not null)
);

create index if not exists hub_projects_created_at_idx on public.hub_projects (created_at desc);
create index if not exists hub_projects_kind_idx on public.hub_projects (kind);

alter table public.hub_profiles enable row level security;
alter table public.hub_projects enable row level security;

grant select on public.hub_projects to anon, authenticated;
grant select on public.hub_profiles to authenticated;
grant usage, select on sequence public.hub_projects_id_seq to service_role, authenticated;

create or replace function public.is_hub_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.hub_profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_hub_admin() from public;
grant execute on function public.is_hub_admin() to authenticated, service_role;

drop policy if exists "Public can read published hub projects" on public.hub_projects;
create policy "Public can read published hub projects"
on public.hub_projects for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert hub projects" on public.hub_projects;
create policy "Admins can insert hub projects"
on public.hub_projects for insert
to authenticated
with check (public.is_hub_admin());

drop policy if exists "Admins can update hub projects" on public.hub_projects;
create policy "Admins can update hub projects"
on public.hub_projects for update
to authenticated
using (public.is_hub_admin()) with check (public.is_hub_admin());

drop policy if exists "Admins can delete hub projects" on public.hub_projects;
create policy "Admins can delete hub projects"
on public.hub_projects for delete
to authenticated
using (public.is_hub_admin());

drop policy if exists "Users can read their own hub profile" on public.hub_profiles;
create policy "Users can read their own hub profile"
on public.hub_profiles for select
to authenticated
using (id = auth.uid());

-- O bucket é público porque o catálogo público precisa exibir capas e vídeos sem login.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'hub-media',
  'hub-media',
  true,
  26214400,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm', 'video/quicktime']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read hub media" on storage.objects;
create policy "Public can read hub media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'hub-media');

drop policy if exists "Admins can upload hub media" on storage.objects;
create policy "Admins can upload hub media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'hub-media' and public.is_hub_admin());

drop policy if exists "Admins can update hub media" on storage.objects;
create policy "Admins can update hub media"
on storage.objects for update
to authenticated
using (bucket_id = 'hub-media' and public.is_hub_admin())
with check (bucket_id = 'hub-media' and public.is_hub_admin());

drop policy if exists "Admins can delete hub media" on storage.objects;
create policy "Admins can delete hub media"
on storage.objects for delete
to authenticated
using (bucket_id = 'hub-media' and public.is_hub_admin());

-- Após o primeiro cadastro, a API marca essa conta como admin. Para promover manualmente:
-- update public.hub_profiles set role = 'admin' where email = 'seu-email@dominio.com';
